schemes:
  solarized_dark: &dark
    primary:
      background: '#002b36' # base03
      foreground: '#839496' # base0

    # Cursor colors
    cursor:
      text:   '#002b36' # base03
      cursor: '#839496' # base0

    # Normal colors
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    # Bright colors
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00`
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3

  afterglow: &afterglow
    # Default colors
    primary:
      background: '0x2c2c2c'
      foreground: '0xd6d6d6'

      dim_foreground:    '0xdbdbdb'
      bright_foreground: '0xd9d9d9'
      dim_background:    '0x202020' # not sure
      bright_background: '0x3a3a3a' # not sure

    # Cursor colors
    cursor:
      text:   '0x2c2c2c'
      cursor: '0xd9d9d9'

    # Normal colors
    normal:
      black:   '0x1c1c1c'
      red:     '0xbc5653'
      green:   '0x909d63'
      yellow:  '0xebc17a'
      blue:    '0x7eaac7'
      magenta: '0xaa6292'
      cyan:    '0x86d3ce'
      white:   '0xcacaca'

    # Bright colors
    bright:
      black:   '0x636363'
      red:     '0xbc5653'
      green:   '0x909d63'
      yellow:  '0xebc17a'
      blue:    '0x7eaac7'
      magenta: '0xaa6292'
      cyan:    '0x86d3ce'
      white:   '0xf7f7f7'

    # Dim colors
    dim:
      black:   '0x232323'
      red:     '0x74423f'
      green:   '0x5e6547'
      yellow:  '0x8b7653'
      blue:    '0x556b79'
      magenta: '0x6e4962'
      cyan:    '0x5c8482'
      white:   '0x828282'

colors: *afterglow

window:
  padding:
    x: 10
    y: 10

font:
  size: 8
  normal:
    family: Cascadia Code
    style: Regular
  bold:
    family: Cascadia Code
    style: Bold
  italic:
    family: Cascadia Code
    style: Italic